services:

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    restart: always
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
    networks:
      - debt-net

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - debt-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  service-user:
    build: ./service-user
    container_name: service-user
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
      - config-server
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
    networks:
      - debt-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-user
      - service-registry
      - config-server
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
    networks:
      - debt-net

networks:
  debt-net:
