server:
  port: 8761

spring:
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false
    peer-eureka-nodes: http://service-registry:8761/eureka